basic test setup and fixes
Slesarew/Kalatori-backend pull request #4
Opened 2024-05-17 07:42 UTC by Vovke

2024-05-17 21:51 UTC, Slesarew requested changes
please revert panics and unwraps to proper errors

2024-05-17 21:51 UTC, Slesarew commented on src/chain/rpc.rs
> +    let count = 100; // I expect it to always work, but will it actually?
```suggestion
    let count = 100; // TODO make full scan just in case
```

2024-05-17 21:51 UTC, Slesarew commented on src/chain/rpc.rs
> +            panic!();
are you reverting this to panic?

2024-05-17 21:51 UTC, Slesarew commented on Cargo.toml
> +reqwest = { version = "0.11", features = ["json"] }
shouldn't this be dev-deps?

2024-05-18 14:52 UTC, Vovke commented on src/lib.rs
> +pub mod definitions;
to export definitions into tests

2024-05-18 22:10 UTC, Slesarew approved these changes

2024-05-18 22:10 UTC, merged